# Define the allowed RADIUS clients (e.g., Access Points)
client Anyone {
	ipaddr = 0.0.0.0/0
	proto = *
	nas_type = other
	secret = replace_with_client_SECRET
	require_message_authenticator = no
	limit {
		max_connections = 10
		lifetime = 0
		idle_timeout = 30
	}
}
